### ISSUE TITLE
qndl? :)

### ISSUE THREAD

**Issue by 097115** [serhanekmekci/dotfiles#1]
Hi!

Sorry if it may sound rude or too interfering but your `newsboat` config [mentions](https://github.com/serhanekmekci/dotfiles/blob/f901c53972e2abc88e5cfc4bdfb61241d23ab8f6/.config/newsboat/config#L34) some program or script named `qndl` -- could you share what is it? Any relation to Quandl by any chance? :)

**Comment by serhanekmekci** [comment]
It is Luke Smith's script for downloading Youtube videos in queue.

https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/qndl
